default: &default
  adapter: postgresql
  encoding: unicode
  username: champ
  password: champ
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo_production
  username: champ
  password: champ


